### ISSUE TITLE
Add a continuous build and continuous test status

### ISSUE THREAD

**Issue by wkirschenmann** [aneoconsulting/PENE#29]
At the creation of this issue, some tests are not working:

```
The following tests FAILED:
         21 - test_oth_counters.double_oth_scalar_tests.test_count (Failed)
         23 - test_oth_counters.float_oth_scalar_tests.test_count (Failed)
        136 - /tmp/pene_build/Test/test_backend/test_backend.py (Failed)
        137 - /tmp/pene_build/Test/test_backend_verrou/test_verrou.py (Failed)
```

**Comment by wkirschenmann** [comment]
Test #21:

```
1/4 Test  #21: test_oth_counters.double_oth_scalar_tests.test_count ......***Failed    3.35 sec

======================================================================
FAIL: test_count (test_oth_counters.double_oth_scalar_tests) [nLoop:2  a:0   b:1]
Checks that instruction count is correct
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pene_build/Test/test_counters/testCounterGenerator.py", line 161, in test_count
    self.checkwithoutresult(self.counterMode, self.tls, self.precision, self.operation, self.mode,  2, 0, 1)
  File "/tmp/pene_build/Test/test_counters/testCounterGenerator.py", line 126, in checkwithoutresult
    nbOps = self.getNbOps(output, prec, op, mode)
  File "/tmp/pene_build/Test/test_counters/testCounterGenerator.py", line 60, in getNbOps
    self.assertRegex(output, p)
AssertionError: Regex didn't match: 'double *?oth *?scalar *?(?P<value>\\d+)' not found in '===============================================\n    PENE: Pin Enabled Numerical Exploration    \n===============================================\nValidating inputs for version_module\nValidating inputs for counters_module\nChecking configuration: FP instructions count with counter-mode=1\nChecking configuration: FP instructions count with counter-tls=0\nValidating inputs for symbol_list_generator_module\nChecking configuration: symbol list generation - no symbol file will be generated\nValidating inputs for replace_module\nChecking configuration: instruction replacement mode with fp-replace=0\nModules initialization.\nInitialization: FP instructions count.\nSet counters to "trace" instrumentation mode.\nInitialization: symbol list generation.\nInitialization: replace module.\nfp-replace None mode : no instrumentation\nModules initialized.\nThis program is used for tests purposes only. If used to check the ability of the pintool to count operations, input have to be chosen so that the result is 0 to avoid fp->string conversion.\nEnd of execution. Code returned 0.\nDisplaying counters\' information : \n----------------------------------------------------------\nPrec.  Op.     Vect.      Total      sse      avx   avx512\n----------------------------------------------------------\nf2d    cvt    scalar         2        0        2        0\n----------------------------------------------------------\n'

======================================================================
FAIL: test_count (test_oth_counters.double_oth_scalar_tests) [nLoop:9  a:0   b:1]
Checks that instruction count is correct
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pene_build/Test/test_counters/testCounterGenerator.py", line 163, in test_count
    self.checkwithoutresult(self.counterMode, self.tls, self.precision, self.operation, self.mode, 9, 0, 1)
  File "/tmp/pene_build/Test/test_counters/testCounterGenerator.py", line 126, in checkwithoutresult
    nbOps = self.getNbOps(output, prec, op, mode)
  File "/tmp/pene_build/Test/test_counters/testCounterGenerator.py", line 60, in getNbOps
    self.assertRegex(output, p)
AssertionError: Regex didn't match: 'double *?oth *?scalar *?(?P<value>\\d+)' not found in '===============================================\n    PENE: Pin Enabled Numerical Exploration    \n===============================================\nValidating inputs for version_module\nValidating inputs for counters_module\nChecking configuration: FP instructions count with counter-mode=1\nChecking configuration: FP instructions count with counter-tls=0\nValidating inputs for symbol_list_generator_module\nChecking configuration: symbol list generation - no symbol file will be generated\nValidating inputs for replace_module\nChecking configuration: instruction replacement mode with fp-replace=0\nModules initialization.\nInitialization: FP instructions count.\nSet counters to "trace" instrumentation mode.\nInitialization: symbol list generation.\nInitialization: replace module.\nfp-replace None mode : no instrumentation\nModules initialized.\nThis program is used for tests purposes only. If used to check the ability of the pintool to count operations, input have to be chosen so that the result is 0 to avoid fp->string conversion.\nEnd of execution. Code returned 0.\nDisplaying counters\' information : \n----------------------------------------------------------\nPrec.  Op.     Vect.      Total      sse      avx   avx512\n----------------------------------------------------------\nf2d    cvt    scalar         2        0        2        0\n----------------------------------------------------------\n'

----------------------------------------------------------------------
Ran 1 test in 3.011s
```

**Comment by wkirschenmann** [comment]
#136 & #137 : pytest was missing.
==> need to add a check in the cmake configure

**Comment by wkirschenmann** [comment]
continuous build already there and problems already described in other issues. I close this one.
